### ISSUE TITLE
pre release does not appear to work

### ISSUE THREAD

**Issue by steveoh** [dotnet-outdated/dotnet-outdated#179]
```sh
$ dotnet outdated --version
A .NET Core global tool to list outdated Nuget packages.
3.2.0
```

```sh
$ dotnet outdated --pre-release
Specify --help for a list of available options and commands.
Unhandled exception. McMaster.Extensions.CommandLineUtils.CommandParsingException: Missing value for option 'pre-release'
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.ProcessOption(OptionArgument arg)
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.ProcessNext()
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.Process()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Parse(String[] args)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at DotNetOutdated.Program.Main(String[] args) in /home/runner/work/dotnet-outdated/dotnet-outdated/src/DotNetOutdated/Program.cs:line 124
```

```sh
$ dotnet outdated -pre                             
Specify --help for a list of available options and commands.
Unhandled exception. McMaster.Extensions.CommandLineUtils.CommandParsingException: Missing value for option 'pre'
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.ProcessOption(OptionArgument arg)
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.ProcessNext()
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.Process()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Parse(String[] args)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at DotNetOutdated.Program.Main(String[] args) in /home/runner/work/dotnet-outdated/dotnet-outdated/src/DotNetOutdated/Program.cs:line 124
```

**Comment by steveoh** [comment]
Nevermind. I didn't read the help. This is a much better error message.

```sh
$ dotnet outdated --pre-release true
Unhandled exception. McMaster.Extensions.CommandLineUtils.CommandParsingException: Invalid value specified for pre-release. Allowed values are: Auto, Always, Never.
 ---> System.FormatException: Invalid value specified for pre-release. Allowed values are: Auto, Always, Never.
   at McMaster.Extensions.CommandLineUtils.Abstractions.EnumParser.<>c__DisplayClass0_0.<Create>b__0(String argName, String value, CultureInfo culture)
   at McMaster.Extensions.CommandLineUtils.Abstractions.ValueParser.DelegatingValueParser`1.Parse(String argName, String value, CultureInfo culture)
   at McMaster.Extensions.CommandLineUtils.Abstractions.ValueParser.DelegatingValueParser.Parse(String argName, String value, CultureInfo culture)
   at McMaster.Extensions.CommandLineUtils.Abstractions.ValueParserProvider.GenericParserAdapter`1.McMaster.Extensions.CommandLineUtils.Abstractions.IValueParser.Parse(String argName, String value, CultureInfo culture)
   at McMaster.Extensions.CommandLineUtils.Conventions.OptionAttributeConventionBase`1.<>c__DisplayClass0_0.<AddOption>b__1(ParseResult _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.HandleParseResult(ParseResult parseResult)
   --- End of inner exception stack trace ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.HandleParseResult(ParseResult parseResult)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Parse(String[] args)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at DotNetOutdated.Program.Main(String[] args) in /home/runner/work/dotnet-outdated/dotnet-outdated/src/DotNetOutdated/Program.cs:line 124
```
