### ISSUE TITLE
Exception while upgrading current release version with --pre-release Always --version-lock Major

### ISSUE THREAD

**Issue by wengfatt** [dotnet-outdated/dotnet-outdated#365]
If I want to upgrade my current stable branch with all release nuget package to latest nuget package (pre release), I will get below exception. 

 **dotnet-outdated --upgrade --pre-release Always  --version-lock Major**

Analyzing dependencies...Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at System.String.StartsWith(String value, StringComparison comparisonType)
   at NuGet.Versioning.FloatRange.Satisfies(NuGetVersion version)
   at NuGet.Versioning.VersionRange.IsBetter(NuGetVersion current, NuGetVersion considering)
   at NuGet.Versioning.VersionRange.FindBestMatch(IEnumerable`1 versions)
   at DotNetOutdated.Core.Services.NuGetPackageResolutionService.ResolvePackageVersions(String packageName, NuGetVersion referencedVersion, IEnumerable`1 sources, VersionRange currentVersionRange, VersionLock versionLock, PrereleaseReporting prerelease, NuGetFramework targetFrameworkName, String projectFilePath, Boolean isDevelopmentDependency, Int32 olderThanDays, Boolean ignoreFailedSources) in /home/runner/work/dotnet-outdated/dotnet-outdated/src/DotNetOutdated.Core/Services/NuGetPackageResolutionService.cs:line 60
   at DotNetOutdated.Program.AddOutdatedDependencyIfNeeded(Project project, TargetFramework targetFramework, Dependency dependency, ConcurrentBag`1 outdatedDependencies) in /home/runner/work/dotnet-outdated/dotnet-outdated/src/DotNetOutdated/Program.cs:line 483
   at DotNetOutdated.Program.AddOutdatedFrameworkIfNeeded(TargetFramework targetFramework, Project project, ConcurrentBag`1 outdatedFrameworks, IConsole console) in /home/runner/work/dotnet-outdated/dotnet-outdated/src/DotNetOutdated/Program.cs:line 470
   at DotNetOutdated.Program.AddOutdatedProjectsIfNeeded(Project project, ConcurrentBag`1 outdatedProjects, IConsole console) in /home/runner/work/dotnet-outdated/dotnet-outdated/src/DotNetOutdated/Program.cs:line 439
   at DotNetOutdated.Program.AnalyzeDependencies(List`1 projects, IConsole console) in /home/runner/work/dotnet-outdated/dotnet-outdated/src/DotNetOutdated/Program.cs:line 407
   at DotNetOutdated.Program.OnExecute(CommandLineApplication app, IConsole console) in /home/runner/work/dotnet-outdated/dotnet-outdated/src/DotNetOutdated/Program.cs:line 187
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at DotNetOutdated.Program.Main(String[] args) in /home/runner/work/dotnet-outdated/dotnet-outdated/src/DotNetOutdated/Program.cs:line 129
[1]    39660 abort      dotnet-outdated --upgrade --pre-release Always --include "ecs." --include

**Comment by yenneferofvengerberg** [comment]
I have the same issue. Apparently, upgrading to the latest nuget.* packages (6.4.0) solves the issue. If that is true, I'll open a PR
