### ISSUE TITLE
System.IO.InvalidDataException thrown when solution only contains a single nuke project

### ISSUE THREAD

**Issue by DaveSenn** [dotnet-outdated/dotnet-outdated#368]
Running `dotnet outdated` results in the following error for one of my repos:

```
Analyzing project(s)...Unhandled exception. System.IO.InvalidDataException: Found invalid data while decoding.
   at NuGet.ProjectModel.DependencyGraphSpec.Load(String path)
   at DotNetOutdated.Core.Services.DependencyGraphService.GenerateDependencyGraph(String projectPath) in /home/runner/work/dotnet-outdated/dotnet-outdated/src/DotNetOutdated.Core/Services/DependencyGraphService.cs:line 45
   at DotNetOutdated.Core.Services.ProjectAnalysisService.AnalyzeProject(String projectPath, Boolean runRestore, Boolean includeTransitiveDependencies, Int32 transitiveDepth) in /home/runner/work/dotnet-outdated/dotnet-outdated/src/DotNetOutdated.Core/Services/ProjectAnalysisService.cs:line 28
   at DotNetOutdated.Program.<OnExecute>b__74_0(String path) in /home/runner/work/dotnet-outdated/dotnet-outdated/src/DotNetOutdated/Program.cs:line 179
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at DotNetOutdated.Program.OnExecute(CommandLineApplication app, IConsole console) in /home/runner/work/dotnet-outdated/dotnet-outdated/src/DotNetOutdated/Program.cs:line 179
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at DotNetOutdated.Program.Main(String[] args) in /home/runner/work/dotnet-outdated/dotnet-outdated/src/DotNetOutdated/Program.cs:line 129
```

The repo is somewhat special as the only .NET code/project is a single [nuke](https://nuke.build/) build project.
I've attached a small repro to the issue.

Intresting is the solution file which contains no active build configuration and only a single project:
```

Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 17
VisualStudioVersion = 17.4.33110.190
MinimumVisualStudioVersion = 10.0.40219.1
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "_build", "build\_build.csproj", "{E665DC24-E1D9-4B5A-8736-BFB309B09911}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{E665DC24-E1D9-4B5A-8736-BFB309B09911}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{E665DC24-E1D9-4B5A-8736-BFB309B09911}.Release|Any CPU.ActiveCfg = Release|Any CPU
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
	GlobalSection(ExtensibilityGlobals) = postSolution
		SolutionGuid = {2E901272-E552-4F32-AB9C-9DD52A54E291}
	EndGlobalSection
EndGlobal
````

The problem seems to originate here:
```
        public DependencyGraphSpec GenerateDependencyGraph(string projectPath)
        {
            var dgOutput = _fileSystem.Path.Combine(_fileSystem.Path.GetTempPath(), _fileSystem.Path.GetTempFileName());
                
            string[] arguments = {"msbuild", $"\"{projectPath}\"", "/t:Restore,GenerateRestoreGraphFile", $"/p:RestoreGraphOutputPath=\"{dgOutput}\""};

            var runStatus = _dotNetRunner.Run(_fileSystem.Path.GetDirectoryName(projectPath), arguments);

            if (runStatus.IsSuccess)
            {
                /*
                    TempDirectory is a hacky workaround for DependencyGraphSpec(JObject)
                    being deprecated. Unfortunately it looks like the only alternative
                    is to load the file locally. Which is ok normally, but complicates
                    testing.
                */
                using (var tempDirectory = new TempDirectory())
                {
                    var dependencyGraphFilename = System.IO.Path.Combine(tempDirectory.DirectoryPath, "DependencyGraph.json");
                    var dependencyGraphText = _fileSystem.File.ReadAllText(dgOutput);
                    System.IO.File.WriteAllText(dependencyGraphFilename, dependencyGraphText);
                    return DependencyGraphSpec.Load(dependencyGraphFilename);
                }
            }

            throw new CommandValidationException($"Unable to process the project `{projectPath}. Are you sure this is a valid .NET Core or .NET Standard project type?" +
                                                 $"{Environment.NewLine}{Environment.NewLine}Here is the full error message returned from the Microsoft Build Engine:{Environment.NewLine}{Environment.NewLine}{runStatus.Output} - {runStatus.Errors} - exit code: {runStatus.ExitCode}");
        }
```

`dependencyGraphText` the content of the file `dgOutput` is a empty string.
The output of msbuild is:
```
MSBuild version 17.4.0+18d5aef85 for .NET
  Determining projects to restore...
C:\Program Files\dotnet\sdk\7.0.100\NuGet.targets(132,5): warning : Unable to find a project to restore! [C:\_git\Demo\OnlineHelp.sln]
C:\Program Files\dotnet\sdk\7.0.100\NuGet.targets(164,5): warning : Unable to find a project to restore! [C:\_git\Demo\OnlineHelp.sln]
```

[Demo.zip](https://github.com/dotnet-outdated/dotnet-outdated/files/10320462/Demo.zip)

**Comment by DaveSenn** [comment]
Did you find the time to look at this? Would you like help to fix the issue?
