### ISSUE TITLE
Error "Found invalid data while decoding".

### ISSUE THREAD

**Issue by UweKeim** [dotnet-outdated/dotnet-outdated#526]
Running this command line:

```cmd
dotnet-outdated "c:\myfolder\mysln.sln" -u
```

On that SLN:

```sln
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 17
VisualStudioVersion = 17.0.31815.197
MinimumVisualStudioVersion = 10.0.40219.1
Project("{A0786B88-2ADB-4C21-ABE8-AA2D79766269}") = "PhpServerComponent", "PhpServerComponent\PhpServerComponent.phpproj", "{2A8E39B9-5D74-4AD5-9021-09B376068984}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{2A8E39B9-5D74-4AD5-9021-09B376068984}.Release|Any CPU.ActiveCfg = Release|Any CPU
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
	GlobalSection(ExtensibilityGlobals) = postSolution
		SolutionGuid = {3CD6D34D-D6F0-424C-9A20-A300D6018781}
	EndGlobalSection
EndGlobal
```

Results on dotnet-outdated being crashing with:

```txt
Unhandled exception. System.IO.InvalidDataException: Found invalid data while decoding.
   at NuGet.ProjectModel.DependencyGraphSpec.Load(String path)
   at DotNetOutdated.Core.Services.DependencyGraphService.GenerateDependencyGraph(String projectPath) in /home/runner/work/dotnet-outdated/dotnet-outdated/src/DotNetOutdated.Core/Services/DependencyGraphService.cs:line 46
   at DotNetOutdated.Core.Services.ProjectAnalysisService.AnalyzeProject(String projectPath, Boolean runRestore, Boolean includeTransitiveDependencies, Int32 transitiveDepth) in /home/runner/work/dotnet-outdated/dotnet-outdated/src/DotNetOutdated.Core/Services/ProjectAnalysisService.cs:line 28
   at DotNetOutdated.Program.<OnExecute>b__78_0(String path) in /home/runner/work/dotnet-outdated/dotnet-outdated/src/DotNetOutdated/Program.cs:line 185
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at DotNetOutdated.Program.OnExecute(CommandLineApplication app, IConsole console) in /home/runner/work/dotnet-outdated/dotnet-outdated/src/DotNetOutdated/Program.cs:line 185
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at DotNetOutdated.Program.Main(String[] args) in /home/runner/work/dotnet-outdated/dotnet-outdated/src/DotNetOutdated/Program.cs:line 137
```

Please note that the solution only contains a `.phpproj` project reference created with [DevSense](https://www.devsense.com).

It seems to make no difference whether the refered `.phpproj` file actually exists or not.

### My question

Could you please make dotnet-outdated _not_ creash in such a scenario?

I'm running dotnet-outdated from within a script that walks all SLN files in a certain folder tree and it would help me if dotnet-outdated simply ignores unexpected project types (instead of crashing).

Otherwise I probably would have to manually parse the SLN for `.csproj` files.

**Comment by UweKeim** [comment]
Seems my issue here is a a duplicate/related to #368.
