### ISSUE TITLE
error running dotnet-outdated

### ISSUE THREAD

**Issue by jkone27** [dotnet-outdated/dotnet-outdated#577]
net8 solution and projects

```
dotnet --version
8.0.101
```

and constantly getting this error

```
Analyzing project(s)...Unhandled exception. System.ComponentModel.Win32Exception (13): An error occurred trying to start process '/Users/admin/Repositories/travix.customerhub/dotnet' with working directory '/Users/admin/Repositories/travix.customerhub'. Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at DotNetOutdated.Core.Services.DotNetRunner.Run(String workingDirectory, String[] arguments) in /home/runner/work/dotnet-outdated/dotnet-outdated/src/DotNetOutdated.Core/Services/DotNetRunner.cs:line 32
   at DotNetOutdated.Core.Services.DependencyGraphService.GenerateDependencyGraphAsync(String projectPath) in /home/runner/work/dotnet-outdated/dotnet-outdated/src/DotNetOutdated.Core/Services/DependencyGraphService.cs:line 41
   at DotNetOutdated.Core.Services.ProjectAnalysisService.AnalyzeProjectAsync(String projectPath, Boolean runRestore, Boolean includeTransitiveDependencies, Int32 transitiveDepth) in /home/runner/work/dotnet-outdated/dotnet-outdated/src/DotNetOutdated.Core/Services/ProjectAnalysisService.cs:line 29
   at DotNetOutdated.Program.OnExecute(CommandLineApplication app, IConsole console) in /home/runner/work/dotnet-outdated/dotnet-outdated/src/DotNetOutdated/Program.cs:line 189
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at DotNetOutdated.Program.Main(String[] args) in /home/runner/work/dotnet-outdated/dotnet-outdated/src/DotNetOutdated/Program.cs:line 141
   ```

**Comment by symbiogenesis** [comment]
Check the file and folder permissions? Use sudo? Run the terminal in admin mode? Install the dotnet CLI into a more standard location?

There is a dotnet installer script which can help you install to non-standard locations.

https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script
